name: "football_dbt"
version: "1.0.0"
config-version: 2

profile: "football_dbt"

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  football_dbt:
    staging:
      materialized: view
    marts:
      materialized: table
